// Code generated by "stringer -type=DataKind -trimprefix=DataKind"; DO NOT EDIT.

package ru_nalog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataKindInvalid-0]
	_ = x[DataKindSTLV-1]
	_ = x[DataKindBool-2]
	_ = x[DataKindUint-3]
	_ = x[DataKindVLN-4]
	_ = x[DataKindFVLN-5]
	_ = x[DataKindTime-6]
	_ = x[DataKindString-7]
	_ = x[DataKindBytes-8]
}

const _DataKind_name = "InvalidSTLVBoolUintVLNFVLNTimeStringBytes"

var _DataKind_index = [...]uint8{0, 7, 11, 15, 19, 22, 26, 30, 36, 41}

func (i DataKind) String() string {
	if i >= DataKind(len(_DataKind_index)-1) {
		return "DataKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataKind_name[_DataKind_index[i]:_DataKind_index[i+1]]
}
