// WARNING: This file has automatically been generated
// Code generated by generate-tags.py DO NOT EDIT.

package ru_nalog

var builtinTags = [...]TagDesc{
	{DataKindBool, 1001, 1, false},    // признак автоматического режима
	{DataKindBool, 1002, 1, false},    // признак автономного режима
	{DataKindString, 1005, 256, true}, // адрес оператора перевода
	{DataKindString, 1008, 64, true},  // телефон или электронный адрес покупателя
	{DataKindString, 1009, 256, true}, // адрес расчетов
	{DataKindTime, 1012, 4, false},    // дата, время
	{DataKindString, 1013, 20, true},  // заводской номер ККТ
	{DataKindString, 1016, 12, false}, // ИНН оператора перевода
	{DataKindString, 1017, 12, false}, // ИНН ОФД
	{DataKindString, 1018, 12, false}, // ИНН пользователя
	{DataKindVLN, 1020, 6, true},      // сумма расчета, указанного в чеке (БСО)
	{DataKindString, 1021, 64, true},  // кассир
	{DataKindUint, 1022, 1, false},    // код ответа ОФД
	{DataKindFVLN, 1023, 8, true},     // количество предмета расчета
	{DataKindString, 1026, 64, true},  // наименование оператора перевода
	{DataKindString, 1030, 128, true}, // наименование предмета расчета
	{DataKindVLN, 1031, 6, true},      // сумма по чеку (БСО) наличными
	{DataKindString, 1036, 20, true},  // номер автомата
	{DataKindString, 1037, 20, false}, // регистрационный номер ККТ
	{DataKindUint, 1038, 4, false},    // номер смены
	{DataKindUint, 1040, 4, false},    // номер ФД
	{DataKindString, 1041, 16, false}, // номер ФН
	{DataKindUint, 1042, 4, false},    // номер чека за смену
	{DataKindVLN, 1043, 6, true},      // стоимость предмета расчета с учетом скидок и наценок
	{DataKindString, 1044, 24, true},  // операция платежного агента
	{DataKindString, 1046, 256, true}, // наименование ОФД
	{DataKindString, 1048, 256, true}, // наименование пользователя
	{DataKindBool, 1050, 1, false},    // признак исчерпания ресурса ФН
	{DataKindBool, 1051, 1, false},    // признак необходимости срочной замены ФН
	{DataKindBool, 1052, 1, false},    // признак переполнения памяти ФН
	{DataKindBool, 1053, 1, false},    // признак превышения времени ожидания ответа ОФД
	{DataKindUint, 1054, 1, false},    // признак расчета
	{DataKindUint, 1055, 1, false},    // применяемая система налогообложения
	{DataKindBool, 1056, 1, false},    // признак шифрования
	{DataKindUint, 1057, 1, false},    // признак агента
	{DataKindSTLV, 1059, 1024, true},  // предмет расчета
	{DataKindString, 1060, 256, true}, // адрес сайта ФНС
	{DataKindUint, 1062, 1, false},    // системы налогообложения
	{DataKindSTLV, 1068, 9, true},     // сообщение оператора для ФН
	{DataKindString, 1073, 19, true},  // телефон платежного агента
	{DataKindString, 1074, 19, true},  // телефон оператора по приему платежей
	{DataKindString, 1075, 19, true},  // телефон оператора перевода
	{DataKindBytes, 1077, 6, false},   // ФПД
	{DataKindBytes, 1078, 16, true},   // ФПО
	{DataKindVLN, 1079, 6, true},      // цена за единицу предмета расчета с учетом скидок и наценок
	{DataKindVLN, 1081, 6, true},      // сумма по чеку (БСО) электронными
	{DataKindSTLV, 1084, 320, true},   // дополнительный реквизит пользователя
	{DataKindString, 1085, 64, true},  // наименование дополнительного реквизита пользователя
	{DataKindString, 1086, 256, true}, // значение дополнительного реквизита пользователя
	{DataKindUint, 1097, 4, false},    // количество непереданных ФД
	{DataKindTime, 1098, 4, false},    // дата и время первого из непереданных ФД
	{DataKindUint, 1101, 1, false},    // код причины перерегистрации
	{DataKindVLN, 1102, 6, true},      // сумма НДС чека по ставке 18%
	{DataKindVLN, 1103, 6, true},      // сумма НДС чека по ставке 10%
	{DataKindVLN, 1104, 6, true},      // сумма расчета по чеку с НДС по ставке 0%
	{DataKindVLN, 1105, 6, true},      // сумма расчета по чеку без НДС
	{DataKindVLN, 1106, 6, true},      // сумма НДС чека по расч. ставке 18/118
	{DataKindVLN, 1107, 6, true},      // сумма НДС чека по расч. ставке 10/110
	{DataKindBool, 1108, 1, false},    // признак ККТ для расчетов только в Интернет
	{DataKindBool, 1109, 1, false},    // признак расчетов за услуги
	{DataKindBool, 1110, 1, false},    // признак АС БСО
	{DataKindUint, 1111, 4, false},    // общее количество ФД за смену
	{DataKindUint, 1116, 4, false},    // номер первого непереданного документа
	{DataKindString, 1117, 64, true},  // адрес электронной почты отправителя чека
	{DataKindUint, 1118, 4, false},    // количество кассовых чеков (БСО) за смену
	{DataKindBool, 1126, 1, false},    // признак проведения лотереи
	{DataKindSTLV, 1129, 116, true},   // счетчики операций «приход»
	{DataKindSTLV, 1130, 116, true},   // счетчики операций «возврат прихода»
	{DataKindSTLV, 1131, 116, true},   // счетчики операций «расход»
	{DataKindSTLV, 1132, 116, true},   // счетчики операций «возврат расхода»
	{DataKindSTLV, 1133, 216, true},   // счетчики операций по чекам коррекции
	{DataKindUint, 1134, 4, false},    // количество чеков (БСО) со всеми признаками расчетов
	{DataKindUint, 1135, 4, false},    // количество чеков по признаку расчетов
	{DataKindVLN, 1136, 6, true},      // итоговая сумма в чеках (БСО) наличными денежными средствами
	{DataKindVLN, 1138, 6, true},      // итоговая сумма в чеках (БСО) электронными средствами платежа
	{DataKindVLN, 1139, 6, true},      // сумма НДС по ставке 18%
	{DataKindVLN, 1140, 6, true},      // сумма НДС по ставке 10%
	{DataKindVLN, 1141, 6, true},      // сумма НДС по расч. ставке 18/118
	{DataKindVLN, 1142, 6, true},      // сумма НДС по расч. ставке 10/110
	{DataKindVLN, 1143, 6, true},      // сумма расчетов с НДС по ставке 0%
	{DataKindUint, 1144, 4, false},    // количество чеков коррекции
	{DataKindSTLV, 1145, 100, true},   // счетчики коррекций «приход»
	{DataKindSTLV, 1146, 100, true},   // счетчики коррекций «расход»
	{DataKindUint, 1148, 4, false},    // количество самостоятельных корректировок
	{DataKindUint, 1149, 4, false},    // количество корректировок по предписанию
	{DataKindVLN, 1151, 6, true},      // сумма коррекций НДС по ставке 18%
	{DataKindVLN, 1152, 6, true},      // сумма коррекций НДС по ставке 10%
	{DataKindVLN, 1153, 6, true},      // сумма коррекций НДС по расч. ставке 18/118
	{DataKindVLN, 1154, 6, true},      // сумма коррекций НДС расч. ставке 10/110
	{DataKindVLN, 1155, 6, true},      // сумма коррекций с НДС по ставке 0%
	{DataKindSTLV, 1157, 708, true},   // счетчики итогов ФН
	{DataKindSTLV, 1158, 708, true},   // счетчики итогов непереданных ФД
	{DataKindBytes, 1162, 32, true},   // код товарной номенклатуры
	{DataKindString, 1171, 19, true},  // телефон поставщика
	{DataKindBool, 1173, 1, false},    // тип коррекции
	{DataKindSTLV, 1174, 292, true},   // основание для коррекции
	{DataKindString, 1177, 256, true}, // описание коррекции
	{DataKindTime, 1178, 4, false},    // дата документа основания для коррекции
	{DataKindString, 1179, 32, true},  // номер документа основания для коррекции
	{DataKindVLN, 1183, 6, true},      // сумма расчетов без НДС
	{DataKindVLN, 1184, 6, true},      // сумма коррекций без НДС
	{DataKindString, 1187, 256, true}, // место расчетов
	{DataKindString, 1188, 8, true},   // версия ККТ
	{DataKindUint, 1189, 1, false},    // версия ФФД ККТ
	{DataKindUint, 1190, 1, false},    // версия ФФД ФН
	{DataKindString, 1191, 64, true},  // дополнительный реквизит предмета расчета
	{DataKindString, 1192, 16, true},  // дополнительный реквизит чека (БСО)
	{DataKindBool, 1193, 1, false},    // признак проведения азартных игр
	{DataKindSTLV, 1194, 708, true},   // счетчики итогов смены
	{DataKindString, 1197, 16, true},  // единица измерения предмета расчета
	{DataKindVLN, 1198, 6, true},      // размер НДС за единицу предмета расчета
	{DataKindUint, 1199, 1, false},    // ставка НДС
	{DataKindVLN, 1200, 6, true},      // сумма НДС за предмет расчета
	{DataKindVLN, 1201, 6, true},      // общая итоговая сумма в чеках (БСО)
	{DataKindString, 1203, 12, false}, // ИНН кассира
	{DataKindUint, 1205, 4, false},    // коды причин изменения сведений о ККТ
	{DataKindUint, 1206, 1, false},    // сообщение оператора
	{DataKindBool, 1207, 1, false},    // признак торговли подакцизными товарами
	{DataKindString, 1208, 256, true}, // сайт чеков
	{DataKindUint, 1209, 1, false},    // версия ФФД
	{DataKindUint, 1212, 1, false},    // признак предмета расчета
	{DataKindUint, 1213, 2, false},    // ресурс ключей ФП
	{DataKindUint, 1214, 1, false},    // признак способа расчета
	{DataKindVLN, 1215, 6, true},      // сумма по чеку (БСО) предоплатой (зачетом аванса и (или) предыдущих платежей)
	{DataKindVLN, 1216, 6, true},      // сумма по чеку (БСО) постоплатой (в кредит)
	{DataKindVLN, 1217, 6, true},      // сумма по чеку (БСО) встречным предоставлением
	{DataKindVLN, 1218, 6, true},      // итоговая сумма в чеках (БСО) предоплатами (авансами)
	{DataKindVLN, 1219, 6, true},      // итоговая сумма в чеках (БСО) постоплатами (кредитами)
	{DataKindVLN, 1220, 6, true},      // итоговая сумма в чеках (БСО) встречными предоставлениями
	{DataKindBool, 1221, 1, false},    // признак установки принтера в автомате
	{DataKindUint, 1222, 1, false},    // признак агента по предмету расчета
	{DataKindSTLV, 1223, 512, true},   // данные агента
	{DataKindSTLV, 1224, 512, true},   // данные поставщика
	{DataKindString, 1225, 256, true}, // наименование поставщика
	{DataKindString, 1226, 12, false}, // ИНН поставщика

}
